/**
 * API template
 * API template description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CharacterDto } from './characterDto';
import { UserDto } from './userDto';


export interface CommandDto { 
    id: string;
    userId?: string;
    user?: UserDto;
    products?: Array<CharacterDto>;
    createdDate?: Date;
}

