/**
 * API template
 * API template description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RegisterRequest { 
    /**
     * user email
     */
    mail: string;
    /**
     * user password
     */
    password: string;
    /**
     * user username
     */
    username: string;
}

